@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0

'' ingredientes singleton? ok mas precisa ter quantidade que ainda tem
interface singleton {}
''class Alface implements singleton {}
''class Tomate implements singleton {}
''class Pão implements singleton {}
''class Carne implements singleton {}

'' hamburguers pre-prontso tem singleton também
interface Burguer implements singleton, Order {}
class hamburguerPadraoCasa implements Burguer {}
class hamburguerXBurguer implements Burguer {}
class hamburguerXBacon implements Burguer {}
class hamburguerDoubleCheese implements Burguer {}

'' hamburguer tipo subway vc pode ir montando o seu
'' builder
interface builder {}
class HamburguerBuilder implements Burguer, builder {}

class Pedido implements builder {}

'' factory method (para criar hamburgueres de diferentes tipos)
interface BurgerFactory implements Burguer {
    public getBurger(String burguerName): Burguer
}

'' abstract factory

interface ComboAbstractFactory {
    public createBurger(): Burguer
    public createDrink(): Drink
    public createExtra(): Extra
}

class DoubleBaconFactory implements ComboAbstractFactory {}
class CheeseLoveFactory implements ComboAbstractFactory {}

'' prototype para clonar hamburguer (futuramente podemos fazer algo para alterar um hamburguer de cópia em pedido)
interface Prototype<T> {
    public clone(): T
}

class Combo implements Prototype, Order {}
class Drink implements Prototype, Order {}
interface Extra implements Prototype, Order {}

'' decorator
'' -> para pedido delivery (frete no preço)
'' -> para pedido no local (couver artístico + taxa garçom)
'' -> para alterações de produtos no pedido

abstract class PedidoDecorator {}
class DeliveryPedidoDecorator implements PedidoDecorator {}
class CouverArtisticoPedidoDecorator implements PedidoDecorator {}
class ServicoPedidoDecorator implements PedidoDecorator {}


''strategy - Formas de Pagamento
interface FormaPagamento {}
class Pix implements FormaPagamento {}
class Cartao implements FormaPagamento {}
class Dinheiro implements FormaPagamento {}
class Pedido {}
Pedido ..> FormaPagamento


''state
interface PedidoEstado {}
class PedidoEstadoRealizado implements PedidoEstado, singleton {}
class PedidoEstadoEmPreparo implements PedidoEstado, singleton {}
class PedidoEstadoPronto implements PedidoEstado, singleton {}
class PedidoEstadoEmEntrega implements PedidoEstado, singleton {}
class PedidoEstadoEntregue implements PedidoEstado, singleton {}
class PedidoEstadoCancelado implements PedidoEstado, singleton {}

Pedido -> PedidoEstado
Pedido ..> PedidoEstado


''facade
class SistemaDeliveryFacade {}

SistemaDeliveryFacade ..> HamburguerBuilder
SistemaDeliveryFacade ..> Pedido
SistemaDeliveryFacade ..> DeliveryPedidoDecorator
SistemaDeliveryFacade ..> FormaPagamento


''observer
interface ObservadorPedido {
+ atualizar(status: PedidoEstado)
}
class AppCliente implements ObservadorPedido {}
class AppMotoboy implements ObservadorPedido {}

Pedido o-> ObservadorPedido


''chain of responsibility
abstract class ValidadorPedido {}
class V[118;1:3ualidadorAreaEntrega extends ValidadorPedido {}
class ValidadorPagamento extends ValidadorPedido {}
class ValidadorEstoque extends ValidadorPedido {}

ValidadorPedido -> ValidadorPedido
Pedido ..> ValidadorPedido


''flyweight
interface IngredienteFlyweight {}
class Alface implements IngredienteFlyweight {}
class Tomate implements IngredienteFlyweight {}
class Pão implements IngredienteFlyweight {}
class Carne implements IngredienteFlyweight {}

class IngredienteFactory {}
class ItemPedido {}

IngredienteFactory -> IngredienteFlyweight
ItemPedido -> IngredienteFlyweight
HamburguerBuilder ..> ItemPedido

'' visitor: visita o pedido

interface Visitor {}
class KitchenVisitor implements Visitor {}
class OrderPriceVisitor implements Visitor {}
class PackageVisitor implements Visitor {}

'' bridge

interface OrderType {}
class DeliveryOrder implements OrderType {}
class PickupOrder implements OrderType {}

interface OrderOrigin {}
class WhatsappOrder implements OrderOrigin {}
class AppOrder implements OrderOrigin {}

'' adapter

interface APIAdapter {}
class IFoodAdapter {}
class RappiAdapter {}

'' proxy

interface CacheProxy {}
class MenuProxy implements CacheProxy {}
'' para nao precisar, por exemplo, reler o banco para pegar o menu

'' composite

interface Order {
    public getNextItem()
    public getFullOrder()
}
'' ja deixei uns itens seguindo Order (estao acima)
@enduml

