@startuml
hide empty description

state "Pedido Realizado" as Realizado
state "Pedido Em Preparo" as EmPreparo
state "Pedido Pronto" as Pronto
state "Pedido Em Entrega" as EmEntrega
state "Pedido Entregue" as Entregue
state "Pedido Cancelado" as Cancelado

[*] --> Realizado
Realizado--> EmPreparo
EmPreparo --> Pronto
Pronto --> EmEntrega
EmEntrega --> Entregue
Entregue --> [*]

Realizado --> Cancelado
Cancelado --> [*]

@enduml
